### PR TITLE
Limit logging

### PR DESCRIPTION
**Pull request by williamli80**
1. Change open/tellg/close to a single stat.

Signed-off-by: Nan Li bjlinan@cn.ibm.com

---

This change is [Reviewable](https://reviewable.io/reviews/openbmc/phosphor-event/17)

### CODE REVIEW

**Comment by causten** [comment]
This code passes unit tests and looks good

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-event/17)_

**Comment by williamli80** [comment]
Changed the usage of strerror().

**Comment by causten** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-event/17)_

**Comment by anoo1** [comment]
:lgtm:

<details><summary>

<i>Previously, williamli80 wrote…</i></summary>



> Changed the usage of strerror().</details>

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/openbmc/phosphor-event/17#-:-KHur7YWTDpXgiV0q0x4:1417088721)_

**Pull request merged**
